dist: focal
language: python

python:
  - '3.9'
  - '3.12'

before_install:
  - pip install --upgrade setuptools packaging
  - if ! [ -f ./src/GRCh37.tar.gz ]; then wget --connect-timeout=10 --tries=20 ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz -P ./src/; fi

install:
  - pip install .

cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/
  
before_script:
  - python3 install_genome.py $TRAVIS_BUILD_DIR/src/

script: python3 test.py
